version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    depends_on:
      - mysql
    env_file:
      - app/.env
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    volumes:
      - type: bind
        source: ./app/
        target: /srv/esin/
        consistency: delegated
      - type: bind
        source: ./docker/php/composer_cache
        target: /.composer/cache
        consistency: delegated
  nginx:
    image: nginx:1.15.3-alpine
    depends_on:
      - php
    restart: on-failure
    stop_signal: SIGQUIT
    volumes:
      - type: bind
        source: ./app/public/
        target: /srv/esin/public
      - type: bind
        source: ./docker/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - ${NET_NGINX_PORT}:80
  mysql:
    image: mariadb:10.5.9
    restart: on-failure
    env_file:
      - .env.local
    ports:
      - ${NET_MYSQL_PORT}:3306
    volumes:
      - type: bind
        source: ./docker/mysql/data
        target: /var/lib/mysql
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - ${NET_ADMINER_PORT}:8080